# k8s-edge-scheduler : custom kubernetes scheduler for placing pods based on location data
# Copyright (c) 2019, Lukas Steiner, Deutsche Telekom AG
# contact: opensource@telekom.de

# This file is licensed under the terms of the 3-Clause BSD License  [SPDX: BSD3-Clause]. 
# For Details see the file LICENSE on the top level of the project repository.

variables:
  REPO_NAME: github.com/telekom/k8s-edge-scheduler
  SCHEDULER_IMAGE: ${CI_REGISTRY_IMAGE}/k8s-edge-scheduler:${CI_COMMIT_REF_NAME}
  SCHEDULER_AGENT_IMAGE: ${CI_REGISTRY_IMAGE}/k8s-edge-scheduler-agent:${CI_COMMIT_REF_NAME}

before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

stages:
  - build
  - image

compile:
  stage: build
  image: golang
  variables:
    GOOS: linux
    CGO_ENABLED: "0"
  script:
    - go get ./...
    - go build -o build/edge-scheduler
    - go build -o build/edge-scheduler-agent ./agent 
  artifacts:
    expire_in: 1 week
    paths:
      - build/*

image-build:
  stage: image
  image: docker
  dependencies: 
    - compile
  script:
    - docker build -t ${SCHEDULER_IMAGE} .
    - docker build -t ${SCHEDULER_AGENT_IMAGE} -f agent/Dockerfile .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push ${SCHEDULER_IMAGE}
    - docker push ${SCHEDULER_AGENT_IMAGE}
