# k8s-edge-scheduler : custom kubernetes scheduler for placing pods based on location data
# Copyright (c) 2019, Lukas Steiner, Deutsche Telekom AG
# contact: opensource@telekom.de

# This file is licensed under the terms of the 3-Clause BSD License  [SPDX: BSD3-Clause]. 
# For Details see the file LICENSE on the top level of the project repository.

kind: Pod
apiVersion: v1
metadata:
  name: edge-scheduler-agent
  labels:
    app: edge-scheduler-agent
spec:
  serviceAccount: scheduler-agent
  containers:
  - name: edge-scheduler-agent
    image: k8s-edge-scheduler-agent
    env:
      - name: PROXYNAMESPACE
        value: edge-cloud
      - name: NSIGNOREREGEX
        value: edge-cloud
      - name: INFLUXADDR
        value: http://influxdb:8086
      - name: INFLUXUSER
        value: influx
      - name: INFLUXPASSWORD
        value: influx
      - name: JAEGERADDR
        value: ":6831"
      - name: DEBUG
        value: "false"
    ports:
    - containerPort: 6831
      protocol: UDP
---
kind: Service
apiVersion: v1
metadata:
  name: edge-scheduler-agent
  labels:
    app: edge-scheduler-agent
spec:
  selector:
    app: edge-scheduler-agent
  ports:
  - name: jaeger-agent
    port: 6831
    protocol: UDP
